parameters:
  version: '1.0'

services:
  _defaults:
    autowire: true
    public: false
    bind:
      string $version: '%version%'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['app.command']

  App\:
    resource: '../src/*'

  App\App:
    public: true
    arguments:
      - !tagged_iterator app.command